######################################################################
# Automatically generated by qmake (3.0) Fri Sep 18 18:35:50 2015
######################################################################

TEMPLATE = app
TARGET = Persons
INCLUDEPATH += .

# Input
HEADERS += Person.h \
    student.h \
    faculty.h \
    voter.h
SOURCES += main.cpp Person.cpp \
    student.cpp \
    faculty.cpp \
    voter.cpp
